"""empty message

Revision ID: e5856d2a9cf8
Revises: 
Create Date: 2022-05-12 19:45:26.066704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5856d2a9cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('tipo_ususario', sa.String(length=250), nullable=True),
    sa.Column('detalle', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=250), nullable=False),
    sa.Column('social', sa.String(length=250), nullable=True),
    sa.Column('cliente_activo', sa.Boolean(), nullable=True),
    sa.Column('proveedor_activo', sa.Boolean(), nullable=True),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('detalle', sa.String(length=250), nullable=True),
    sa.Column('fecha_activacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.Column('nombre_tipo_servicio', sa.String(length=250), nullable=False),
    sa.Column('nombre_tipo_sub_servicio', sa.String(length=250), nullable=False),
    sa.Column('detalle_tipo_servicio', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'proveedor_id', 'nombre_tipo_servicio', 'nombre_tipo_sub_servicio', 'detalle_tipo_servicio', 'status_active', name='debe_tener_una_sola_coincidencia')
    )
    op.create_table('evaluacion_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=250), nullable=False),
    sa.Column('evaluate_status', sa.Boolean(), nullable=False),
    sa.Column('detalle_servicio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resultado_evaluacion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_servicio_id'], ['tipo_servicio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('precio_orden', sa.Float(), nullable=False),
    sa.Column('precio_total_orden', sa.Float(), nullable=False),
    sa.Column('status_orden_recibida', sa.Boolean(), nullable=False),
    sa.Column('status_orden_cancelada', sa.Boolean(), nullable=False),
    sa.Column('status_orden_aceptada', sa.Boolean(), nullable=False),
    sa.Column('status_orden_progreso', sa.Boolean(), nullable=False),
    sa.Column('detalle_servicio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detalle_servicio_id'], ['tipo_servicio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_servicio')
    op.drop_table('evaluacion_proveedor')
    op.drop_table('tipo_servicio')
    op.drop_table('user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
