"""empty message

Revision ID: f015488c8867
Revises: 
Create Date: 2022-05-11 22:20:31.702459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f015488c8867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('tipo_ususario', sa.String(length=250), nullable=False),
    sa.Column('social', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('detalle', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('tipo_ususario', sa.String(length=250), nullable=False),
    sa.Column('social', sa.String(length=250), nullable=False),
    sa.Column('cliente_activo', sa.Boolean(), nullable=False),
    sa.Column('proveedor_activo', sa.Boolean(), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('detalle', sa.String(length=250), nullable=False),
    sa.Column('fecha_activacion', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('status_active', sa.Boolean(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('detalle', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'proveedor_id', 'detalle', name='debe_tener_una_sola_coincidencia')
    )
    op.create_table('tipo_sub_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=True),
    sa.Column('status_activo', sa.Boolean(), nullable=False),
    sa.Column('detalle', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=True),
    sa.Column('evaluate_status', sa.Boolean(), nullable=False),
    sa.Column('detalle', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_sub_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluacion_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=250), nullable=False),
    sa.Column('evaluate_status', sa.Boolean(), nullable=False),
    sa.Column('detalle_servicio_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('resultado_evaluacion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['detalle_servicio_id'], ['detalle_servicio.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orden_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('precio_orden', sa.Float(), nullable=False),
    sa.Column('precio_total_orden', sa.Float(), nullable=False),
    sa.Column('status_orden_recibido', sa.Boolean(), nullable=False),
    sa.Column('status_orden_cancelada', sa.Boolean(), nullable=False),
    sa.Column('status_orden_aceptada', sa.Boolean(), nullable=False),
    sa.Column('status_orden_progreso', sa.Boolean(), nullable=False),
    sa.Column('detalle_servicio_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['detalle_servicio_id'], ['detalle_servicio.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_servicio')
    op.drop_table('evaluacion_proveedor')
    op.drop_table('detalle_servicio')
    op.drop_table('tipo_sub_servicio')
    op.drop_table('tipo_servicio')
    op.drop_table('user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
